language: node_js
node_js:
  - "6"
script:
  - npm run test
after_success:
  - npm run build-storybook
  - npm run deploy-storybook
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master